"""API schemas."""

from naming_check_backend.presentation.schemas.contracts import (
    DeliveryChannel,
    ErrorCode,
    ErrorContext,
    ErrorDetail,
    ErrorResponse,
    FlowType,
    LogoSimilarityMatch,
    LogoSimilaritySearchResponse,
    MatchCandidate,
    ProcessingStatus,
    SimilarityBreakdown,
    Stage2StatusInfo,
    Stage2WebhookRequest,
    Stage2WebhookResponse,
    TextSimilarityMatch,
    TextSimilaritySearchRequest,
    TextSimilaritySearchResponse,
)

__all__ = [
    "DeliveryChannel",
    "ErrorCode",
    "ErrorContext",
    "ErrorDetail",
    "ErrorResponse",
    "FlowType",
    "LogoSimilarityMatch",
    "LogoSimilaritySearchResponse",
    "MatchCandidate",
    "ProcessingStatus",
    "SimilarityBreakdown",
    "Stage2StatusInfo",
    "Stage2WebhookRequest",
    "Stage2WebhookResponse",
    "TextSimilarityMatch",
    "TextSimilaritySearchRequest",
    "TextSimilaritySearchResponse",
]
